spring.application.name=tastytome

spring.devtools.restart.enabled=true
spring.devtools.restart.poll-interval=1000
spring.devtools.restart.quiet-period=400

spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTHENTIK_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AUTHENTIK_JWKS_URI}